name: Sync

on:
  schedule:
    - cron: '0 21 * * 2,0' # Tue & Sun 9PM UTC
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add upstream https://github.com/folbricht/routedns.git  

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Check for upstream changes
      id: check_upstream
      run: |
        UPSTREAM_BRANCH="master"
        LOCAL_BRANCH="master"

        # Check if the upstream branch has commits not present in the local branch
        if [ $(git rev-list ${LOCAL_BRANCH}..upstream/${UPSTREAM_BRANCH} --count) -gt 0 ]; then
          echo "Upstream changes detected."
          echo "merge_needed=true" >> $GITHUB_ENV
        else
          echo "No upstream changes detected."
          echo "merge_needed=false" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Merge changes
      if: env.merge_needed == 'true'
      run: |
        git merge upstream/${UPSTREAM_BRANCH} --no-commit --no-ff -Xtheirs --allow-unrelated-histories || true
        # Exclude YAML files from .github/workflows/ directory from being synchronized
        git reset HEAD .github/workflows/*.yaml .github/workflows/*.yml || true
        git checkout -- .github/workflows/*.yaml .github/workflows/*.yml || true
        git add -u

    - name: Check for changes
      if: env.merge_needed == 'true'
      id: check_changes
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "changes=true" >> $GITHUB_ENV
        fi

    - name: Commit changes
      if: env.changes == 'true'
      run: git commit -m "Sync upstream changes"

    - name: Push changes
      if: env.changes == 'true'
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
