name: Sync

on:
  schedule:
    - cron: '0 21 * * 2,0' # Tue & Sun 9PM UTC
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add upstream https://github.com/folbricht/routedns.git  

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Check if merge is necessary
      id: check_merge
      run: |
        echo "Checking for new commits from upstream..."
        UPSTREAM_REPO="folbricht/routedns"
        FORK_REPO="${{ github.repository }}"
        UPSTREAM_BRANCH="master"
        FORK_BRANCH="master"

        # Get the latest commit SHA from the upstream repository
        UPSTREAM_LATEST_COMMIT=$(curl -s https://api.github.com/repos/$UPSTREAM_REPO/commits/$UPSTREAM_BRANCH | jq -r '.sha')
        if [ -z "$UPSTREAM_LATEST_COMMIT" ]; then
          echo "Failed to get the latest commit from upstream."
          echo "::set-output name=merge_needed::false"
          exit 0
        fi
        echo "UPSTREAM_LATEST_COMMIT=$UPSTREAM_LATEST_COMMIT"

        # Get the latest commit SHA from the forked repository
        FORK_LATEST_COMMIT=$(curl -s https://api.github.com/repos/$FORK_REPO/commits/$FORK_BRANCH | jq -r '.sha')
        if [ -z "$FORK_LATEST_COMMIT" ]; then
          echo "Failed to get the latest commit from the fork."
          echo "::set-output name=merge_needed::false"
          exit 0
        fi
        echo "FORK_LATEST_COMMIT=$FORK_LATEST_COMMIT"

        # Compare the commits to check if there are any new commits in the upstream repository
        COMPARE_URL="https://api.github.com/repos/$UPSTREAM_REPO/compare/$FORK_LATEST_COMMIT...$UPSTREAM_LATEST_COMMIT"
        COMPARE_RESULT=$(curl -s $COMPARE_URL | jq -r '.status')
        echo "COMPARE_RESULT=$COMPARE_RESULT"
        
        if [ "$COMPARE_RESULT" = "behind" ]; then
          echo "Changes detected, merge needed."
          echo "::set-output name=merge_needed::true"
        else
          echo "No changes to sync."
          echo "::set-output name=merge_needed::false"
        fi
      shell: sh

    - name: Merge changes
      if: steps.check_merge.outputs.merge_needed == 'true'
      run: |
        git merge --no-commit --no-ff -Xtheirs --allow-unrelated-histories upstream/master || true
        # Exclude YAML files from .github/workflows/ directory from being synchronized
        git reset HEAD .github/workflows/*.yaml .github/workflows/*.yml || true
        git checkout -- .github/workflows/*.yaml .github/workflows/*.yml || true
        git add -u

    - name: Check for changes
      if: steps.check_merge.outputs.merge_needed == 'true'
      id: changes
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

    - name: Commit changes
      if: steps.changes.outputs.changes == 'true'
      run: git commit -m "Sync upstream changes"

    - name: Push changes
      if: steps.changes.outputs.changes == 'true'
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
