name: Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily, adjust the schedule as needed
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add upstream https://github.com/folbricht/routedns.git  

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Ensure local master branch exists
      run: |
        if [ -z "$(git branch --list master)" ]; then
          git checkout -b master
        else
          git checkout master
        fi

    - name: Merge changes
      run: |
        git merge --no-commit --no-ff --allow-unrelated-histories upstream/master || true
        # Resolve conflicts by preferring upstream changes
        git diff --name-only --diff-filter=U | while read -r file; do
          if [[ "$file" != .github/workflows/*.yaml ]]; then
            git checkout --theirs "$file"
            git add "$file"
          fi
        done
        for file in .github/workflows/*.yaml; do
          if [ -e "$file" ]; then
            git reset HEAD "$file"
            git checkout -- "$file"
          else
            git rm --cached "$file"
          fi
        done
        git add -u 

    - name: Commit changes
      run: |
        git commit -m "Sync upstream changes" || echo "No changes to commit"

    - name: Push changes to fork
      run: git push origin master || echo "No changes to push"
